import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const getBaseUrl = () =>
  process.env.FASTAPI_BASE_URL ?? 'http://127.0.0.1:8080';

type RouteParams = Promise<{ appName: string; userId: string }>;

// ─── GET /apps/{appName}/users/{userId}/sessions ──────────────────────────────
// List all sessions for a user.

export async function GET(
  _request: NextRequest,
  { params }: { params: RouteParams },
) {
  try {
    const { appName, userId } = await params;
    const baseUrl = getBaseUrl();
    const upstreamUrl = `${baseUrl.replace(/\/$/, '')}/apps/${encodeURIComponent(appName)}/users/${encodeURIComponent(userId)}/sessions`;

    const response = await fetch(upstreamUrl, {
      method: 'GET',
      headers: { Accept: 'application/json' },
      cache: 'no-store',
    });

    if (!response.ok) {
      return NextResponse.json(
        { error: 'FastAPI backend unavailable' },
        { status: 502 },
      );
    }

    const data = await response.json();
    return NextResponse.json(data);
  } catch {
    return NextResponse.json(
      { error: 'FastAPI backend unavailable' },
      { status: 502 },
    );
  }
}

// ─── POST /apps/{appName}/users/{userId}/sessions ─────────────────────────────
// Create a new session. sessionId is optional; auto-generated by the backend if omitted.

export async function POST(
  request: NextRequest,
  { params }: { params: RouteParams },
) {
  try {
    const { appName, userId } = await params;
    const body = (await request.json()) as {
      sessionId?: string;
      state?: Record<string, unknown>;
    };

    const baseUrl = getBaseUrl();
    const upstreamUrl = `${baseUrl.replace(/\/$/, '')}/apps/${encodeURIComponent(appName)}/users/${encodeURIComponent(userId)}/sessions`;

    const response = await fetch(upstreamUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });

    const data = await response.json().catch(() => ({}));
    return NextResponse.json(data, {
      status: response.ok ? 200 : response.status,
    });
  } catch {
    return NextResponse.json(
      { error: 'FastAPI backend unavailable' },
      { status: 502 },
    );
  }
}
